### ISSUE TITLE
Minio Client SDK: Java Client API Reference - Inconsistent Descriptions

### ISSUE THREAD

**Issue by awwalker** [minio/docs.minio.io#167]
See #166 before fixing.

In the Java Client API Reference docs bucketName and prefix are consistently described as "Bucket name." and "Prefix string. List objects whose name starts with prefix." respectively. 

However, in all the other docs these fields are described as "Name of the bucket." and "The prefix of the of the objects that should be listed"

**Comment by deekoder** [comment]
I will fix this.

**Comment by deekoder** [comment]
Done. Please check.

**Comment by awwalker** [comment]
Mine still shows in the Java Client API Reference docs bucketName descriptions being "Bucket name." Not "Name of the bucket."

**Comment by awwalker** [comment]
Looks like you only changed it in the tables where there was also a prefix. But bucketName is throughout the doc.

**Comment by awwalker** [comment]
Went back through and fixed the others. Should be good now.
